name: supabase_basic
description: "A premium Flutter UI showcase app."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  pinput: ^5.0.1
  animate_do: ^3.3.4
  flutter_staggered_animations: ^1.1.1
  iconsax: ^0.0.8
  supabase_flutter: ^2.12.0
  provider: ^6.1.5+1
  google_sign_in: ^7.2.0
  flutter_dotenv: ^6.0.0
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
